# Generated by Django 3.0 on 2019-12-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=30)),
                ('task_discription', models.CharField(max_length=1400)),
            ],
        ),
    ]
