# Generated by Django 3.0 on 2019-12-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='taskitem', name='task_id',),
    ]
