# Generated by Django 3.0 on 2019-12-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_taskitem_task_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskItem',
            new_name='Task',
        ),
    ]
