# Generated by Django 3.0 on 2019-12-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20191210_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
