# Generated by Django 3.0 on 2019-12-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191211_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
    ]
